{
 "title": "Sweet Pipeline Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Inference Latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "inference_latency_seconds" }
   ]
  },
  {
   "title": "Data Shipments Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "messages_consumed_total" }
   ]
  },
  {
   "title": "Inference Size (Chars)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "inference_size_chars" }
   ]
  }
 ]
}